config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'rest#index'
  get 'rest/index'
  resources :rest, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :nickname, presence: true, length: { maximum: 6 }
         validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
         validates :password, presence: true, length: { minimum: 6 }, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!



  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :password_confirmation])
  end


  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/rest_controller.rb
class RestController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
  end
  
  def show
    @user = User.find(params[:id])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lest_helper.rb
module LestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lest/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restly</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

</head>
<header>
        <div class="header-content">
        <h1 class="header-title">Restly</h1>
    </header>
    <nav>
        <a href="#">コラム</a>
        <a href="#">記録</a>
        <a href="#">マイページ</a>
    </nav>
    <div class="main-content">
        <div class="section">
            <div class="section-title">休憩</div>
            <div class="circle">クイックスタート</div>
            <div class="circle">休憩詳細設定</div>
        </div>
        <div class="section">
            <div class="section-title">やらないことリスト</div>
            <div class="circle">例えば<br>物を多く持たない</div>
            <div class="circle">例えば<br>心から楽しめない<br>飲み会に行かない</div>
            <div class="circle">例えば<br>通勤しない</div>
        </div>
<div class="section">
            <div class="section-title">1分コラムを掲載</div>
            <div class="grid">
                <div class="grid-item">コラム1</div>
                <div class="grid-item">コラム2</div>
                <div class="grid-item">コラム3</div>
                <div class="grid-item">コラム4</div>
                <div class="grid-item">コラム5</div>
                <div class="grid-item">コラム6</div>
            </div>
        </div>
    </div>
    <footer>
        <div class="footer-content">
            <p>利用規約</p>
        </div>
    </footer>
</body>
</html>

app/views/rest/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title translate="no">Restly</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">

</head>
<header>
        <div class="header-content">
           <div class="log">
             <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
             </div>
        <h1 class="header-title" translate="no">Restly</h1>
    </header>
    <nav>
<%= link_to '#', class: 'nav-link' do %>コラム<% end %>
  <%= link_to '#', class: 'nav-link' do %>記録<% end %>
<% if user_signed_in? %>
<%= link_to 'マイページ', rest_path(current_user.id), class: "nav-link" %>
<% else %>
<%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
    <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
  <% end %>

    </nav>
<div class="main-content">
        <div class="time-section">
            <div class="time-circle">
                <div class="time-remaining">タップでスタート</div>
<svg class="progress-ring" width="410" height="410">
            <circle class="progress-ring__circle" stroke="black" stroke-width="4" fill="transparent" r="195" cx="205" cy="205"/>
        </svg>
            </div>
        </div>
    </div>
    <div class="section-title">やらないことリスト</div>
        <div class="not-todo-section">
            <div class="circle">物を多く持たない</div>
            <div class="circle">心から楽しめない<br>飲み会に行かない</div>
            <div class="circle">眠る前に<br>SNSを見ない</div>
        </div>
        <div class="section-title">1分コラムを掲載</div>
<div class="section">
            <div class="grid">
                <div class="grid-item">
                    <img src="<%= asset_path('pexrest.jpg') %>" alt="コラム画像" class="column-image">
                    <h3 class="column-title">タイトル</h3>
                    <button class="read-more-btn">もっと見る</button>
                    </div>
                    <div class="grid-item">
                    <img src="<%= asset_path('pexrest.jpg') %>" alt="コラム画像" class="column-image">
                    <h3 class="column-title">タイトル</h3>
                    <button class="read-more-btn">もっと見る</button>
                    </div>
                    <div class="grid-item">
                    <img src="<%= asset_path('pexrest.jpg') %>" alt="コラム画像" class="column-image">
                    <h3 class="column-title">タイトル</h3>
                    <button class="read-more-btn">もっと見る</button>
                    </div>
                    <div class="grid-item">
                    <img src="<%= asset_path('pexrest.jpg') %>" alt="コラム画像" class="column-image">
                    <h3 class="column-title">タイトル</h3>
                    <button class="read-more-btn">もっと見る</button>
                    </div>
                    <div class="grid-item">
                    <img src="<%= asset_path('pexrest.jpg') %>" alt="コラム画像" class="column-image">
                    <h3 class="column-title">タイトル</h3>
                    <button class="read-more-btn">もっと見る</button>
                    </div>
                    <div class="grid-item">
                    <img src="<%= asset_path('pexrest.jpg') %>" alt="コラム画像" class="column-image">
                    <h3 class="column-title">タイトル</h3>
                    <button class="read-more-btn">もっと見る</button>
                    </div>

            </div>
        </div>
    </div>
    <footer>
        <div class="footer-content">
            利用規約
        </div>
    </footer>
    <script src="index.js"></script>
</body>
</html>

app/views/rest/show.html.erb
<h1>マイページ</h1>

<p>ニックネーム: <%= @user.nickname %></p>